const BT_DISABLE_SENSORS = '\x9b';
const BT_ENABLE_SENSORS = '\x9a';

const BT_DISABLE_PIR = '\x99';
const BT_ENABLE_PIR = '\x98';

const BT_DISABLE_SOUND = '\x97';
const BT_ENABLE_SOUND = '\x96';

const BT_TOGGLE_LIGHT = '\x01';

const BT_SEND_CURRENT_ANALOG_SENSOR_DATA = '\x02';
const BT_SEND_CURRENT_APP_STATE = '\x03';

export default {
  BT_DISABLE_SENSORS,
  BT_ENABLE_SENSORS,
  BT_DISABLE_PIR,
  BT_ENABLE_PIR,
  BT_DISABLE_SOUND,
  BT_ENABLE_SOUND,
  BT_TOGGLE_LIGHT,
  BT_SEND_CURRENT_ANALOG_SENSOR_DATA,
  BT_SEND_CURRENT_APP_STATE,
};
